aloha:
  delete_input: false
  endpoint: http://aloha/aloha_dev/
  max_metadata_files: 64
  max_retries: 3
  pool_size: 3
artemis:
  host: localhost
  password: password
  port: 61616
  user: admin
logging:
  formatter: !!python/object:logging.Formatter
    _fmt: '%(asctime)s - %(levelname)s - %(message)s'
    _style: !!python/object:logging.PercentStyle
      _defaults: null
      _fmt: '%(asctime)s - %(levelname)s - %(message)s'
    datefmt: null
  level: 10
  loki:
    auth: !!python/tuple
    - admin
    - admin
    tags:
      application: MontageManager
    url: http://eng-tools:3100/loki/api/v1/push
    version: '1'
  name: monman
redis:
  db: 0
  flush: false
  host: localhost
  port: 6379
tile_dest: /opt/tiles/
